baseURL = "https://www.vizitorapp.com/"
title = "World #NO. 1 Visitor Management System | Check-in Software | Vizitor"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

########################################################################
########################### LANGUAGE CONFIG ############################
########################################################################


########################################################################
################################ PARAMS ################################
########################################################################

[params]
logo = "/images/vizitor/logo.png"

# App buttons (Hero section)
[[params.apps]]
title = "googlePlay"
url   = "https://play.google.com/store/apps/details?id=com.vizitor.app"
image = "/images/vizitor/playstore.webp"

[[params.apps]]
title = "IOSapp"
url   = "https://apps.apple.com/us/app/vizitor/id1408560525?ls=1"
image = "/images/vizitor/appstore.webp"


# App buttons (Footer)
[[params.appsbtn]]
title = "googlePlay"
url   = "https://play.google.com/store/apps/details?id=com.vizitor.app"
image = "/images/vizitor/playstore-footer.svg"

[[params.appsbtn]]
title = "IOSapp"
url   = "https://apps.apple.com/us/app/vizitor/id1408560525?ls=1"
image = "/images/vizitor/appstore-footer.svg"


########################################################################
############################### MARKUP #################################
########################################################################

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
